# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class ChannelSubscriberResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'offset': 'int',
        'has_more': 'bool',
        'total': 'int',
        'data': 'list[ChannelSubscriber]'
    }

    attribute_map = {
        'offset': 'offset',
        'has_more': 'hasMore',
        'total': 'total',
        'data': 'data'
    }

    def __init__(self, offset=None, has_more=None, total=None, data=None, local_vars_configuration=None):  # noqa: E501
        """ChannelSubscriberResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._offset = None
        self._has_more = None
        self._total = None
        self._data = None
        self.discriminator = None

        if offset is not None:
            self.offset = offset
        if has_more is not None:
            self.has_more = has_more
        if total is not None:
            self.total = total
        if data is not None:
            self.data = data

    @property
    def offset(self):
        """Gets the offset of this ChannelSubscriberResponse.  # noqa: E501

        The number of subscribers skipped  # noqa: E501

        :return: The offset of this ChannelSubscriberResponse.  # noqa: E501
        :rtype: int
        """
        return self._offset

    @offset.setter
    def offset(self, offset):
        """Sets the offset of this ChannelSubscriberResponse.

        The number of subscribers skipped  # noqa: E501

        :param offset: The offset of this ChannelSubscriberResponse.  # noqa: E501
        :type: int
        """

        self._offset = offset

    @property
    def has_more(self):
        """Gets the has_more of this ChannelSubscriberResponse.  # noqa: E501

        True if there are more subscribers  # noqa: E501

        :return: The has_more of this ChannelSubscriberResponse.  # noqa: E501
        :rtype: bool
        """
        return self._has_more

    @has_more.setter
    def has_more(self, has_more):
        """Sets the has_more of this ChannelSubscriberResponse.

        True if there are more subscribers  # noqa: E501

        :param has_more: The has_more of this ChannelSubscriberResponse.  # noqa: E501
        :type: bool
        """

        self._has_more = has_more

    @property
    def total(self):
        """Gets the total of this ChannelSubscriberResponse.  # noqa: E501

        The total number of subscribers  # noqa: E501

        :return: The total of this ChannelSubscriberResponse.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this ChannelSubscriberResponse.

        The total number of subscribers  # noqa: E501

        :param total: The total of this ChannelSubscriberResponse.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def data(self):
        """Gets the data of this ChannelSubscriberResponse.  # noqa: E501


        :return: The data of this ChannelSubscriberResponse.  # noqa: E501
        :rtype: list[ChannelSubscriber]
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ChannelSubscriberResponse.


        :param data: The data of this ChannelSubscriberResponse.  # noqa: E501
        :type: list[ChannelSubscriber]
        """

        self._data = data

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelSubscriberResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChannelSubscriberResponse):
            return True

        return self.to_dict() != other.to_dict()
