# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class UserLeftRoomMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'removed_by_user_id': 'int',
        'member_left_user_id': 'int',
        'information_barrier_remediation': 'bool'
    }

    attribute_map = {
        'removed_by_user_id': 'removedByUserId',
        'member_left_user_id': 'memberLeftUserId',
        'information_barrier_remediation': 'informationBarrierRemediation'
    }

    def __init__(self, removed_by_user_id=None, member_left_user_id=None, information_barrier_remediation=None, local_vars_configuration=None):  # noqa: E501
        """UserLeftRoomMessage - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._removed_by_user_id = None
        self._member_left_user_id = None
        self._information_barrier_remediation = None
        self.discriminator = None

        if removed_by_user_id is not None:
            self.removed_by_user_id = removed_by_user_id
        if member_left_user_id is not None:
            self.member_left_user_id = member_left_user_id
        if information_barrier_remediation is not None:
            self.information_barrier_remediation = information_barrier_remediation

    @property
    def removed_by_user_id(self):
        """Gets the removed_by_user_id of this UserLeftRoomMessage.  # noqa: E501


        :return: The removed_by_user_id of this UserLeftRoomMessage.  # noqa: E501
        :rtype: int
        """
        return self._removed_by_user_id

    @removed_by_user_id.setter
    def removed_by_user_id(self, removed_by_user_id):
        """Sets the removed_by_user_id of this UserLeftRoomMessage.


        :param removed_by_user_id: The removed_by_user_id of this UserLeftRoomMessage.  # noqa: E501
        :type: int
        """

        self._removed_by_user_id = removed_by_user_id

    @property
    def member_left_user_id(self):
        """Gets the member_left_user_id of this UserLeftRoomMessage.  # noqa: E501


        :return: The member_left_user_id of this UserLeftRoomMessage.  # noqa: E501
        :rtype: int
        """
        return self._member_left_user_id

    @member_left_user_id.setter
    def member_left_user_id(self, member_left_user_id):
        """Sets the member_left_user_id of this UserLeftRoomMessage.


        :param member_left_user_id: The member_left_user_id of this UserLeftRoomMessage.  # noqa: E501
        :type: int
        """

        self._member_left_user_id = member_left_user_id

    @property
    def information_barrier_remediation(self):
        """Gets the information_barrier_remediation of this UserLeftRoomMessage.  # noqa: E501


        :return: The information_barrier_remediation of this UserLeftRoomMessage.  # noqa: E501
        :rtype: bool
        """
        return self._information_barrier_remediation

    @information_barrier_remediation.setter
    def information_barrier_remediation(self, information_barrier_remediation):
        """Sets the information_barrier_remediation of this UserLeftRoomMessage.


        :param information_barrier_remediation: The information_barrier_remediation of this UserLeftRoomMessage.  # noqa: E501
        :type: bool
        """

        self._information_barrier_remediation = information_barrier_remediation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserLeftRoomMessage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UserLeftRoomMessage):
            return True

        return self.to_dict() != other.to_dict()
