# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from agent_urllib.configuration import Configuration


class V1AuditTrailInitiatorResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'action': 'str',
        'action_name': 'str',
        'timestamp': 'str',
        'initiator_id': 'str',
        'initiator_username': 'str',
        'initiator_email_address': 'str'
    }

    attribute_map = {
        'action': 'action',
        'action_name': 'actionName',
        'timestamp': 'timestamp',
        'initiator_id': 'initiatorId',
        'initiator_username': 'initiatorUsername',
        'initiator_email_address': 'initiatorEmailAddress'
    }

    def __init__(self, action=None, action_name=None, timestamp=None, initiator_id=None, initiator_username=None, initiator_email_address=None, local_vars_configuration=None):  # noqa: E501
        """V1AuditTrailInitiatorResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._action = None
        self._action_name = None
        self._timestamp = None
        self._initiator_id = None
        self._initiator_username = None
        self._initiator_email_address = None
        self.discriminator = None

        if action is not None:
            self.action = action
        if action_name is not None:
            self.action_name = action_name
        if timestamp is not None:
            self.timestamp = timestamp
        if initiator_id is not None:
            self.initiator_id = initiator_id
        if initiator_username is not None:
            self.initiator_username = initiator_username
        if initiator_email_address is not None:
            self.initiator_email_address = initiator_email_address

    @property
    def action(self):
        """Gets the action of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The audit trail action that has peformed  # noqa: E501

        :return: The action of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this V1AuditTrailInitiatorResponse.

        The audit trail action that has peformed  # noqa: E501

        :param action: The action of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._action = action

    @property
    def action_name(self):
        """Gets the action_name of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The audit trail action name that has peformed  # noqa: E501

        :return: The action_name of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._action_name

    @action_name.setter
    def action_name(self, action_name):
        """Sets the action_name of this V1AuditTrailInitiatorResponse.

        The audit trail action name that has peformed  # noqa: E501

        :param action_name: The action_name of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._action_name = action_name

    @property
    def timestamp(self):
        """Gets the timestamp of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The timestamp when the action has occurred  # noqa: E501

        :return: The timestamp of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this V1AuditTrailInitiatorResponse.

        The timestamp when the action has occurred  # noqa: E501

        :param timestamp: The timestamp of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._timestamp = timestamp

    @property
    def initiator_id(self):
        """Gets the initiator_id of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The user's id that has performed the action  # noqa: E501

        :return: The initiator_id of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._initiator_id

    @initiator_id.setter
    def initiator_id(self, initiator_id):
        """Sets the initiator_id of this V1AuditTrailInitiatorResponse.

        The user's id that has performed the action  # noqa: E501

        :param initiator_id: The initiator_id of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._initiator_id = initiator_id

    @property
    def initiator_username(self):
        """Gets the initiator_username of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The username that has performed the action  # noqa: E501

        :return: The initiator_username of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._initiator_username

    @initiator_username.setter
    def initiator_username(self, initiator_username):
        """Sets the initiator_username of this V1AuditTrailInitiatorResponse.

        The username that has performed the action  # noqa: E501

        :param initiator_username: The initiator_username of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._initiator_username = initiator_username

    @property
    def initiator_email_address(self):
        """Gets the initiator_email_address of this V1AuditTrailInitiatorResponse.  # noqa: E501

        The user's e-mail address that has performed the action  # noqa: E501

        :return: The initiator_email_address of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :rtype: str
        """
        return self._initiator_email_address

    @initiator_email_address.setter
    def initiator_email_address(self, initiator_email_address):
        """Sets the initiator_email_address of this V1AuditTrailInitiatorResponse.

        The user's e-mail address that has performed the action  # noqa: E501

        :param initiator_email_address: The initiator_email_address of this V1AuditTrailInitiatorResponse.  # noqa: E501
        :type: str
        """

        self._initiator_email_address = initiator_email_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1AuditTrailInitiatorResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1AuditTrailInitiatorResponse):
            return True

        return self.to_dict() != other.to_dict()
