# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V1DLPMatchedPolicy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'version': 'str',
        'policy_name': 'str',
        'type': 'str',
        'terms': 'str',
        'diagnostic': 'str'
    }

    attribute_map = {
        'id': 'id',
        'version': 'version',
        'policy_name': 'policyName',
        'type': 'type',
        'terms': 'terms',
        'diagnostic': 'diagnostic'
    }

    def __init__(self, id=None, version=None, policy_name=None, type=None, terms=None, diagnostic=None, local_vars_configuration=None):  # noqa: E501
        """V1DLPMatchedPolicy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._version = None
        self._policy_name = None
        self._type = None
        self._terms = None
        self._diagnostic = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if version is not None:
            self.version = version
        if policy_name is not None:
            self.policy_name = policy_name
        if type is not None:
            self.type = type
        if terms is not None:
            self.terms = terms
        if diagnostic is not None:
            self.diagnostic = diagnostic

    @property
    def id(self):
        """Gets the id of this V1DLPMatchedPolicy.  # noqa: E501

        Id of the policy  # noqa: E501

        :return: The id of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this V1DLPMatchedPolicy.

        Id of the policy  # noqa: E501

        :param id: The id of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def version(self):
        """Gets the version of this V1DLPMatchedPolicy.  # noqa: E501

        Version of the policy  # noqa: E501

        :return: The version of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1DLPMatchedPolicy.

        Version of the policy  # noqa: E501

        :param version: The version of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def policy_name(self):
        """Gets the policy_name of this V1DLPMatchedPolicy.  # noqa: E501

        Name of the policy  # noqa: E501

        :return: The policy_name of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._policy_name

    @policy_name.setter
    def policy_name(self, policy_name):
        """Sets the policy_name of this V1DLPMatchedPolicy.

        Name of the policy  # noqa: E501

        :param policy_name: The policy_name of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._policy_name = policy_name

    @property
    def type(self):
        """Gets the type of this V1DLPMatchedPolicy.  # noqa: E501

        Whether BLOCK or WARN  # noqa: E501

        :return: The type of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1DLPMatchedPolicy.

        Whether BLOCK or WARN  # noqa: E501

        :param type: The type of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def terms(self):
        """Gets the terms of this V1DLPMatchedPolicy.  # noqa: E501

        List of decrypted matched keywords in the policy  # noqa: E501

        :return: The terms of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._terms

    @terms.setter
    def terms(self, terms):
        """Sets the terms of this V1DLPMatchedPolicy.

        List of decrypted matched keywords in the policy  # noqa: E501

        :param terms: The terms of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._terms = terms

    @property
    def diagnostic(self):
        """Gets the diagnostic of this V1DLPMatchedPolicy.  # noqa: E501

        A diagnostic message containing an error message in the event that the decryption of terms failed. May also be present in the case of a successful call if there is useful narrative to return.   # noqa: E501

        :return: The diagnostic of this V1DLPMatchedPolicy.  # noqa: E501
        :rtype: str
        """
        return self._diagnostic

    @diagnostic.setter
    def diagnostic(self, diagnostic):
        """Sets the diagnostic of this V1DLPMatchedPolicy.

        A diagnostic message containing an error message in the event that the decryption of terms failed. May also be present in the case of a successful call if there is useful narrative to return.   # noqa: E501

        :param diagnostic: The diagnostic of this V1DLPMatchedPolicy.  # noqa: E501
        :type: str
        """

        self._diagnostic = diagnostic

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1DLPMatchedPolicy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1DLPMatchedPolicy):
            return True

        return self.to_dict() != other.to_dict()
