# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V1DLPPolicy(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'active': 'bool',
        'content_types': 'list[str]',
        'creation_date': 'int',
        'creator_id': 'str',
        'dictionary_refs': 'list[V1DLPDictionaryRef]',
        'last_disabled_date': 'int',
        'last_updated_date': 'int',
        'name': 'str',
        'policy_id': 'str',
        'scopes': 'list[str]',
        'type': 'str',
        'version': 'str'
    }

    attribute_map = {
        'active': 'active',
        'content_types': 'contentTypes',
        'creation_date': 'creationDate',
        'creator_id': 'creatorId',
        'dictionary_refs': 'dictionaryRefs',
        'last_disabled_date': 'lastDisabledDate',
        'last_updated_date': 'lastUpdatedDate',
        'name': 'name',
        'policy_id': 'policyId',
        'scopes': 'scopes',
        'type': 'type',
        'version': 'version'
    }

    def __init__(self, active=None, content_types=None, creation_date=None, creator_id=None, dictionary_refs=None, last_disabled_date=None, last_updated_date=None, name=None, policy_id=None, scopes=None, type=None, version=None, local_vars_configuration=None):  # noqa: E501
        """V1DLPPolicy - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._active = None
        self._content_types = None
        self._creation_date = None
        self._creator_id = None
        self._dictionary_refs = None
        self._last_disabled_date = None
        self._last_updated_date = None
        self._name = None
        self._policy_id = None
        self._scopes = None
        self._type = None
        self._version = None
        self.discriminator = None

        if active is not None:
            self.active = active
        self.content_types = content_types
        if creation_date is not None:
            self.creation_date = creation_date
        if creator_id is not None:
            self.creator_id = creator_id
        if dictionary_refs is not None:
            self.dictionary_refs = dictionary_refs
        if last_disabled_date is not None:
            self.last_disabled_date = last_disabled_date
        if last_updated_date is not None:
            self.last_updated_date = last_updated_date
        self.name = name
        if policy_id is not None:
            self.policy_id = policy_id
        self.scopes = scopes
        self.type = type
        if version is not None:
            self.version = version

    @property
    def active(self):
        """Gets the active of this V1DLPPolicy.  # noqa: E501

        Indicate whether the policy is active or not  # noqa: E501

        :return: The active of this V1DLPPolicy.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this V1DLPPolicy.

        Indicate whether the policy is active or not  # noqa: E501

        :param active: The active of this V1DLPPolicy.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def content_types(self):
        """Gets the content_types of this V1DLPPolicy.  # noqa: E501

        The list of content types that policy should apply to. Cannot be empty. Policy content types could be either of \"Messages\", \"RoomMeta\", \"SignalMeta\". Default is set to [\"Messages\"] if not specified.   # noqa: E501

        :return: The content_types of this V1DLPPolicy.  # noqa: E501
        :rtype: list[str]
        """
        return self._content_types

    @content_types.setter
    def content_types(self, content_types):
        """Sets the content_types of this V1DLPPolicy.

        The list of content types that policy should apply to. Cannot be empty. Policy content types could be either of \"Messages\", \"RoomMeta\", \"SignalMeta\". Default is set to [\"Messages\"] if not specified.   # noqa: E501

        :param content_types: The content_types of this V1DLPPolicy.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and content_types is None:  # noqa: E501
            raise ValueError("Invalid value for `content_types`, must not be `None`")  # noqa: E501

        self._content_types = content_types

    @property
    def creation_date(self):
        """Gets the creation_date of this V1DLPPolicy.  # noqa: E501

        Creation time of the policy in milliseconds elapsed as of epoch time.   # noqa: E501

        :return: The creation_date of this V1DLPPolicy.  # noqa: E501
        :rtype: int
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this V1DLPPolicy.

        Creation time of the policy in milliseconds elapsed as of epoch time.   # noqa: E501

        :param creation_date: The creation_date of this V1DLPPolicy.  # noqa: E501
        :type: int
        """

        self._creation_date = creation_date

    @property
    def creator_id(self):
        """Gets the creator_id of this V1DLPPolicy.  # noqa: E501

        Numeric userId of the creator  # noqa: E501

        :return: The creator_id of this V1DLPPolicy.  # noqa: E501
        :rtype: str
        """
        return self._creator_id

    @creator_id.setter
    def creator_id(self, creator_id):
        """Sets the creator_id of this V1DLPPolicy.

        Numeric userId of the creator  # noqa: E501

        :param creator_id: The creator_id of this V1DLPPolicy.  # noqa: E501
        :type: str
        """

        self._creator_id = creator_id

    @property
    def dictionary_refs(self):
        """Gets the dictionary_refs of this V1DLPPolicy.  # noqa: E501

        List of dictionaries.  # noqa: E501

        :return: The dictionary_refs of this V1DLPPolicy.  # noqa: E501
        :rtype: list[V1DLPDictionaryRef]
        """
        return self._dictionary_refs

    @dictionary_refs.setter
    def dictionary_refs(self, dictionary_refs):
        """Sets the dictionary_refs of this V1DLPPolicy.

        List of dictionaries.  # noqa: E501

        :param dictionary_refs: The dictionary_refs of this V1DLPPolicy.  # noqa: E501
        :type: list[V1DLPDictionaryRef]
        """

        self._dictionary_refs = dictionary_refs

    @property
    def last_disabled_date(self):
        """Gets the last_disabled_date of this V1DLPPolicy.  # noqa: E501

        Recent disable time of the policy in milliseconds elapsed as of epoch time.   # noqa: E501

        :return: The last_disabled_date of this V1DLPPolicy.  # noqa: E501
        :rtype: int
        """
        return self._last_disabled_date

    @last_disabled_date.setter
    def last_disabled_date(self, last_disabled_date):
        """Sets the last_disabled_date of this V1DLPPolicy.

        Recent disable time of the policy in milliseconds elapsed as of epoch time.   # noqa: E501

        :param last_disabled_date: The last_disabled_date of this V1DLPPolicy.  # noqa: E501
        :type: int
        """

        self._last_disabled_date = last_disabled_date

    @property
    def last_updated_date(self):
        """Gets the last_updated_date of this V1DLPPolicy.  # noqa: E501

        Recent update time of the policy in milliseconds elapsed as of epoch time.  # noqa: E501

        :return: The last_updated_date of this V1DLPPolicy.  # noqa: E501
        :rtype: int
        """
        return self._last_updated_date

    @last_updated_date.setter
    def last_updated_date(self, last_updated_date):
        """Sets the last_updated_date of this V1DLPPolicy.

        Recent update time of the policy in milliseconds elapsed as of epoch time.  # noqa: E501

        :param last_updated_date: The last_updated_date of this V1DLPPolicy.  # noqa: E501
        :type: int
        """

        self._last_updated_date = last_updated_date

    @property
    def name(self):
        """Gets the name of this V1DLPPolicy.  # noqa: E501

        Unique name of a policy, max 30 characters. Cannot be empty. All the leading and trailing blank spaces are trimmed.  # noqa: E501

        :return: The name of this V1DLPPolicy.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this V1DLPPolicy.

        Unique name of a policy, max 30 characters. Cannot be empty. All the leading and trailing blank spaces are trimmed.  # noqa: E501

        :param name: The name of this V1DLPPolicy.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and name is None:  # noqa: E501
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def policy_id(self):
        """Gets the policy_id of this V1DLPPolicy.  # noqa: E501

        Policy Id  # noqa: E501

        :return: The policy_id of this V1DLPPolicy.  # noqa: E501
        :rtype: str
        """
        return self._policy_id

    @policy_id.setter
    def policy_id(self, policy_id):
        """Sets the policy_id of this V1DLPPolicy.

        Policy Id  # noqa: E501

        :param policy_id: The policy_id of this V1DLPPolicy.  # noqa: E501
        :type: str
        """

        self._policy_id = policy_id

    @property
    def scopes(self):
        """Gets the scopes of this V1DLPPolicy.  # noqa: E501

        List of communication scopes. Possible values are \"Internal\" (for Internal conversations) or \"External\" (for External conversations). You can apply both scopes if you set it to [\"Internal\", \"External\"].   # noqa: E501

        :return: The scopes of this V1DLPPolicy.  # noqa: E501
        :rtype: list[str]
        """
        return self._scopes

    @scopes.setter
    def scopes(self, scopes):
        """Sets the scopes of this V1DLPPolicy.

        List of communication scopes. Possible values are \"Internal\" (for Internal conversations) or \"External\" (for External conversations). You can apply both scopes if you set it to [\"Internal\", \"External\"].   # noqa: E501

        :param scopes: The scopes of this V1DLPPolicy.  # noqa: E501
        :type: list[str]
        """
        if self.local_vars_configuration.client_side_validation and scopes is None:  # noqa: E501
            raise ValueError("Invalid value for `scopes`, must not be `None`")  # noqa: E501

        self._scopes = scopes

    @property
    def type(self):
        """Gets the type of this V1DLPPolicy.  # noqa: E501

        Type of policy. Possible values \"Block\" or \"Warn\".  # noqa: E501

        :return: The type of this V1DLPPolicy.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this V1DLPPolicy.

        Type of policy. Possible values \"Block\" or \"Warn\".  # noqa: E501

        :param type: The type of this V1DLPPolicy.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and type is None:  # noqa: E501
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def version(self):
        """Gets the version of this V1DLPPolicy.  # noqa: E501

        The version of a dictionary, in format \"major.minor\". Initial value will set by backend as \"1.0\" when created. Whenever the dictionary version needs to be changed, the minor version by 1 unless minor == 999, then the major version is increased by 1 until it reaches 999.   # noqa: E501

        :return: The version of this V1DLPPolicy.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this V1DLPPolicy.

        The version of a dictionary, in format \"major.minor\". Initial value will set by backend as \"1.0\" when created. Whenever the dictionary version needs to be changed, the minor version by 1 unless minor == 999, then the major version is increased by 1 until it reaches 999.   # noqa: E501

        :param version: The version of this V1DLPPolicy.  # noqa: E501
        :type: str
        """

        self._version = version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1DLPPolicy):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1DLPPolicy):
            return True

        return self.to_dict() != other.to_dict()
