# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from agent_urllib.configuration import Configuration


class V1DLPPoliciesCollectionResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'policies': 'list[V1DLPPolicy]',
        'page': 'int',
        'page_count': 'int'
    }

    attribute_map = {
        'policies': 'policies',
        'page': 'page',
        'page_count': 'pageCount'
    }

    def __init__(self, policies=None, page=None, page_count=None, local_vars_configuration=None):  # noqa: E501
        """V1DLPPoliciesCollectionResponse - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._policies = None
        self._page = None
        self._page_count = None
        self.discriminator = None

        if policies is not None:
            self.policies = policies
        if page is not None:
            self.page = page
        if page_count is not None:
            self.page_count = page_count

    @property
    def policies(self):
        """Gets the policies of this V1DLPPoliciesCollectionResponse.  # noqa: E501

        List of policies  # noqa: E501

        :return: The policies of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :rtype: list[V1DLPPolicy]
        """
        return self._policies

    @policies.setter
    def policies(self, policies):
        """Sets the policies of this V1DLPPoliciesCollectionResponse.

        List of policies  # noqa: E501

        :param policies: The policies of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :type: list[V1DLPPolicy]
        """

        self._policies = policies

    @property
    def page(self):
        """Gets the page of this V1DLPPoliciesCollectionResponse.  # noqa: E501

        Page number of current page  # noqa: E501

        :return: The page of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """Sets the page of this V1DLPPoliciesCollectionResponse.

        Page number of current page  # noqa: E501

        :param page: The page of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :type: int
        """

        self._page = page

    @property
    def page_count(self):
        """Gets the page_count of this V1DLPPoliciesCollectionResponse.  # noqa: E501

        Total number of pages available  # noqa: E501

        :return: The page_count of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :rtype: int
        """
        return self._page_count

    @page_count.setter
    def page_count(self, page_count):
        """Sets the page_count of this V1DLPPoliciesCollectionResponse.

        Total number of pages available  # noqa: E501

        :param page_count: The page_count of this V1DLPPoliciesCollectionResponse.  # noqa: E501
        :type: int
        """

        self._page_count = page_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V1DLPPoliciesCollectionResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V1DLPPoliciesCollectionResponse):
            return True

        return self.to_dict() != other.to_dict()
