# coding: utf-8

"""
    Agent API

    This document refers to Symphony API calls to send and receive messages and content. They need the on-premise Agent installed to perform decryption/encryption of content.  - sessionToken and keyManagerToken can be obtained by calling the authenticationAPI on the symphony back end and the key manager respectively. Refer to the methods described in authenticatorAPI.yaml. - Actions are defined to be atomic, ie will succeed in their entirety or fail and have changed nothing. - If it returns a 40X status then it will have sent no message to any stream even if a request to aome subset of the requested streams would have succeeded. - If this contract cannot be met for any reason then this is an error and the response code will be 50X. - MessageML is a markup language for messages. See reference here: https://rest-api.symphony.com/docs/messagemlv2 - **Real Time Events**: The following events are returned when reading from a real time messages and events stream (\"datafeed\"). These events will be returned for datafeeds created with the v5 endpoints. To know more about the endpoints, refer to Create Messages/Events Stream and Read Messages/Events Stream. Unless otherwise specified, all events were added in 1.46.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from openapi_client.configuration import Configuration


class V3DLPPolicyAppliesTo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'data_type': 'str',
        'action': 'str',
        'rules': 'list[V3DLPRule]'
    }

    attribute_map = {
        'data_type': 'dataType',
        'action': 'action',
        'rules': 'rules'
    }

    def __init__(self, data_type=None, action=None, rules=None, local_vars_configuration=None):  # noqa: E501
        """V3DLPPolicyAppliesTo - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._data_type = None
        self._action = None
        self._rules = None
        self.discriminator = None

        self.data_type = data_type
        self.action = action
        self.rules = rules

    @property
    def data_type(self):
        """Gets the data_type of this V3DLPPolicyAppliesTo.  # noqa: E501

        The list of data types that policy should apply to. Can't be empty. Can be [\"Messages\",\"RoomMeta\", \"SignalMeta\", \"FileContent\", \"FileMeta\"].   # noqa: E501

        :return: The data_type of this V3DLPPolicyAppliesTo.  # noqa: E501
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this V3DLPPolicyAppliesTo.

        The list of data types that policy should apply to. Can't be empty. Can be [\"Messages\",\"RoomMeta\", \"SignalMeta\", \"FileContent\", \"FileMeta\"].   # noqa: E501

        :param data_type: The data_type of this V3DLPPolicyAppliesTo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and data_type is None:  # noqa: E501
            raise ValueError("Invalid value for `data_type`, must not be `None`")  # noqa: E501

        self._data_type = data_type

    @property
    def action(self):
        """Gets the action of this V3DLPPolicyAppliesTo.  # noqa: E501

        Action to be taken on violation detection. Can be [\"Block\", \"Warn\", \"LogOnly\"]. The default is \"LogOnly\".   # noqa: E501

        :return: The action of this V3DLPPolicyAppliesTo.  # noqa: E501
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action):
        """Sets the action of this V3DLPPolicyAppliesTo.

        Action to be taken on violation detection. Can be [\"Block\", \"Warn\", \"LogOnly\"]. The default is \"LogOnly\".   # noqa: E501

        :param action: The action of this V3DLPPolicyAppliesTo.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and action is None:  # noqa: E501
            raise ValueError("Invalid value for `action`, must not be `None`")  # noqa: E501

        self._action = action

    @property
    def rules(self):
        """Gets the rules of this V3DLPPolicyAppliesTo.  # noqa: E501


        :return: The rules of this V3DLPPolicyAppliesTo.  # noqa: E501
        :rtype: list[V3DLPRule]
        """
        return self._rules

    @rules.setter
    def rules(self, rules):
        """Sets the rules of this V3DLPPolicyAppliesTo.


        :param rules: The rules of this V3DLPPolicyAppliesTo.  # noqa: E501
        :type: list[V3DLPRule]
        """
        if self.local_vars_configuration.client_side_validation and rules is None:  # noqa: E501
            raise ValueError("Invalid value for `rules`, must not be `None`")  # noqa: E501

        self._rules = rules

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, V3DLPPolicyAppliesTo):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, V3DLPPolicyAppliesTo):
            return True

        return self.to_dict() != other.to_dict()
