# coding: utf-8

# flake8: noqa

"""
    Login API

    For bots and other on-premise processes to authenticate. Once authenticated, the bot will be able to use the methods described in serviceAPI.yaml and agentAPI.yaml.  Authentication requests will expect the user to pass a token containing user identification information and signed by the user's private key  There will be two implementations of this API, one on your Pod and one on the Key Manager. In order to fully authenticate, an API client will have to call both of these implementations and pass both of the session tokens returned as headers in all subsequent requests to the Symphony API.   # noqa: E501

    The version of the OpenAPI document: 20.10.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

__version__ = "1.0.0"

# import apis into sdk package
from openapi_client_urllib.api.authentication_api import AuthenticationApi

# import ApiClient
from openapi_client_urllib.api_client import ApiClient
from openapi_client_urllib.configuration import Configuration
from openapi_client_urllib.exceptions import OpenApiException
from openapi_client_urllib.exceptions import ApiTypeError
from openapi_client_urllib.exceptions import ApiValueError
from openapi_client_urllib.exceptions import ApiKeyError
from openapi_client_urllib.exceptions import ApiException
# import models into sdk package
from openapi_client_urllib.models.authenticate_extension_app_request import AuthenticateExtensionAppRequest
from openapi_client_urllib.models.authenticate_request import AuthenticateRequest
from openapi_client_urllib.models.error import Error
from openapi_client_urllib.models.extension_app_tokens import ExtensionAppTokens
from openapi_client_urllib.models.token import Token

